table Population-country-1950-1999
	lineageTag: f4e50711-b43c-4d7f-8a87-1272edc6fff6

	column LocID
		dataType: int64
		formatString: 0
		lineageTag: 11dda02a-4c2d-4f21-ad68-cd32aead10f4
		summarizeBy: count
		sourceColumn: LocID

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: db499000-be26-4dac-8d4b-7f0867fb57bc
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Time
		dataType: int64
		formatString: 0
		lineageTag: f7610f15-f98b-4d92-b118-682c8cef0c4b
		summarizeBy: sum
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

	column AgeGrp
		dataType: string
		lineageTag: c41f16c9-1cc7-4190-b2fa-a6ed8dd18156
		summarizeBy: none
		sourceColumn: AgeGrp

		annotation SummarizationSetBy = Automatic

	column AgeGrpStart
		dataType: int64
		formatString: 0
		lineageTag: 346ad218-be03-4a45-965d-ab422ee98f0b
		summarizeBy: sum
		sourceColumn: AgeGrpStart

		annotation SummarizationSetBy = Automatic

	column AgeGrpSpan
		dataType: int64
		formatString: 0
		lineageTag: f3b832f9-7784-4267-a1dd-77197babfcd9
		summarizeBy: sum
		sourceColumn: AgeGrpSpan

		annotation SummarizationSetBy = Automatic

	column PopMale
		dataType: double
		lineageTag: ef5caddb-dd1f-4333-9104-9c8f0cf3ff92
		summarizeBy: sum
		sourceColumn: PopMale

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PopFemale
		dataType: double
		lineageTag: 98ee258a-49a0-4362-9d14-247e14b499ed
		summarizeBy: sum
		sourceColumn: PopFemale

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PopTotal
		dataType: double
		lineageTag: 4b3b3797-d088-4400-b623-787a020f3cd7
		summarizeBy: sum
		sourceColumn: PopTotal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Population-country-1950-1999 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\sautalwar\Downloads\Population\LearnAtHome-main\Source Files\Population_Data\Population-country-1950-1999.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"LocID", Int64.Type}, {"Location", type text}, {"Time", Int64.Type}, {"AgeGrp", type text}, {"AgeGrpStart", Int64.Type}, {"AgeGrpSpan", Int64.Type}, {"PopMale", type number}, {"PopFemale", type number}, {"PopTotal", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

